In [1]:
import numpy as np

In [2]:
def sum(a, b, i):
    value = 0
    for j, g in enumerate(a, start=0):
        value += g * b[j][i]
    return value

def multy(a, b):
    column = []

    for i, k in enumerate(a, start=0):
        if len(a[i]) != len(b):
            raise Exception('Невозможно перемножить матрицу')
        line = []
        for j in range(len(b[i])):
            value = sum(a[i], b, j)
            line.append(value)
        column.append(line)
    return column

In [4]:
a = np.array([[4, 5, 2], [1, -2, 3]])
b = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица AB\n {multy(a, b)}')
print(f'Матрица AB numpy\n{np.dot(a, b)}')

Матрица AB
 [[45, 0], [0, 14]]
Матрица AB numpy
[[45  0]
 [ 0 14]]


In [5]:
a = np.array([[4, 5, 2], [1, -2, 3]])
b = np.array([[4, 3, 4, 9], [5, -2, 5, 1], [2, 3, 8, 2]])
print(f'Матрица AB\n {multy(a, b)}')
print(f'Матрица AB numpy\n{np.dot(a, b)}')

Матрица AB
 [[45, 8, 57, 45], [0, 16, 18, 13]]
Матрица AB numpy
[[45  8 57 45]
 [ 0 16 18 13]]
