In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
# 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга 
# (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], 
# ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. 
# Используя математические операции, посчитать коэффициенты линейной регрессии, 
# приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная).
# Произвести расчет как с использованием intercept, так и без.



x = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

b = (np.mean(x * y) - np.mean(x) * np.mean(y)) / (np.mean(x**2) - np.mean(x) ** 2)
b

2.620538882402765

In [3]:
a = np.mean(y) - b * np.mean(x)
a

444.1773573243596

In [4]:
y_hat = a + b * x
y_hat

array([535.89621821, 562.10160703, 942.07974498, 968.2851338 ,
       548.99891262, 627.61507909, 585.68645697, 837.25818968,
       758.64202321, 732.43663439])

In [5]:
# 
model = LinearRegression()
model.fit(x.reshape((-1, 1)), y)

r_sq = model.score(x.reshape((-1, 1)), y)
print('coefficient of determination:', r_sq)
print('a (intercept):', model.intercept_)
print('b (slope):', model.coef_)

coefficient of determination: 0.7876386635293685
a (intercept): 444.1773573243595
b (slope): [2.62053888]


In [6]:
# Матричный метод
X = x.reshape((-1, 1))
Y = y.reshape((-1, 1))

X = np.hstack([np.ones((len(X), 1)), X])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [7]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T@Y)
B

array([[444.17735732],
       [  2.62053888]])

In [17]:
# 2. Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept). 

def mse(B1, y=y, x=x):
    return np.sum((B1*x-y)**2/len(x))

In [18]:
B1 = 0.1
alfa = 1e-5

for i in range(3000):
    B1 -= alfa*(2/len(x))*np.sum((B1*x-y)*x)
    if i%500 == 0:
        print(f'iteration {i}; B1={B1}, MSE={mse(B1)}')

iteration 0; B1=1.6952808000000004, MSE=298904.5992334053
iteration 500; B1=5.889820420132688, MSE=56516.85841571941
iteration 1000; B1=5.889820420132688, MSE=56516.85841571941
iteration 1500; B1=5.889820420132688, MSE=56516.85841571941
iteration 2000; B1=5.889820420132688, MSE=56516.85841571941
iteration 2500; B1=5.889820420132688, MSE=56516.85841571941
