In [1]:
import numpy as np

In [5]:
# 2-е задание
g = [[1,2,3],[4,0,6],[7,8,9]]
np.linalg.det(g)

59.999999999999986

In [10]:
# 3-е задание
# a
p = np.linalg.inv(g)
print(p)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [11]:
# проверим что обратная матрица верная
np.dot(g, p)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-4.44089210e-16,  1.00000000e+00,  1.11022302e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [29]:
# b
b = np.array([[1, 2, 3, 3], [5, 10, 15, 15], [0, 0, 0, 0], [1, 2, 3, 3]])
print(b)
np.linalg.matrix_rank(b, 0.0001)

[[ 1  2  3  3]
 [ 5 10 15 15]
 [ 0  0  0  0]
 [ 1  2  3  3]]


1

In [26]:
# 4-е задание
a = np.array([1, 5], float)
b = np.array([2, 8], float)
np.dot(a, b)

42.0

In [31]:
# 5-е задание
a = np.array([1, 5, 0], float)
b = np.array([2, 8, 7], float)
c = np.array([7, 1.5, 3], float)
v = np.cross(a, b)
print (np.inner(v, c))

228.5
